general:
    config_mode: "${CONFIG_MODE}"

database:
    hostname: "localhost"
    port: 5402
    username: "${POSTGRES_USERNAME}"
    password: "${POSTGRES_PASSWORD}"
    database: "jarwoLookup"

documenthandler:
    unconverted_types:
        - "pdf"
        - "txt"
        - "svg"
    converted_types:
        - "docx"
        - "doc"
    upload_folder: "./files/upload"
    extract_folder: "./files/extract"
    tesseract_binary: "./backend/binaries/tesseract_bin/tesseract.exe"
    stateful: True

vectorsearch:
    chunk_size: 1000
    max_query_len: 256
    model_path: "xdddddd"

server:
    frontend_entrypoint: "frontend/dist"